Repository openbase/planetsudo.engine, pull requests merged in 2024-02, with the labels that each got.

#22 Feature/#5 random map selection
  src/main/kotlin/org/openbase/planetsudo/view/configuration/ConfigurationPanel.form
  src/main/kotlin/org/openbase/planetsudo/view/configuration/ConfigurationPanel.kt
Labels: tested, code-approved

#28 27 introduce new resource type called tonic
  src/main/kotlin/org/openbase/planetsudo/game/GameObjectImages.kt
  src/main/kotlin/org/openbase/planetsudo/game/strategy/DivineStrategy.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentMock.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Resource.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Kreuzung.kt
  src/main/kotlin/org/openbase/planetsudo/view/level/levelobjects/AgentPanel.kt
  src/main/resources/img/resource-tonic.png
  src/main/resources/img/resource-tonic.xcf
Labels: feature, tested, code-approved

#26 18 new kotlin rule dsl seems to ignore swat team declaration
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/org/openbase/planetsudo/game/strategy/AbstractStrategy.kt
  src/main/kotlin/org/openbase/planetsudo/game/strategy/Rule.kt
  src/main/kotlin/org/openbase/planetsudo/game/strategy/RuleBuilder.kt
  src/main/kotlin/org/openbase/planetsudo/level/AbstractLevel.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentMock.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Mothership.kt
  src/main/kotlin/org/openbase/planetsudo/view/level/levelobjects/MothershipPanel.kt
  src/test/kotlin/org/openbase/planetsudo/game/strategy/AbstractStrategyTest.kt
Labels: bug, tested, code-approved

#30 Implement invisible feature
  src/main/kotlin/org/openbase/planetsudo/game/strategy/DivineStrategy.kt
  src/main/kotlin/org/openbase/planetsudo/level/AbstractLevel.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentMock.kt
  src/main/kotlin/org/openbase/planetsudo/view/level/levelobjects/AbstractLevelObjectPanel.kt
  src/main/kotlin/org/openbase/planetsudo/view/level/levelobjects/AgentPanel.kt
Labels: feature, tested, code-approved

#33 Implement #25 agents should be able to turn towards a resource
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentMock.kt
Labels: tested, code-approved

#31 Implement #14 Agents should query the ResourceType they're carrying
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentMock.kt
Labels: tested, code-approved

#36 Fix bug #19 with create team
  src/main/kotlin/org/openbase/planetsudo/game/Team.kt
  src/main/kotlin/org/openbase/planetsudo/view/MainGUI.kt
  src/main/kotlin/org/openbase/planetsudo/view/configuration/ConfigurationPanel.kt
  src/main/kotlin/org/openbase/planetsudo/view/configuration/CreateTeamFrame.kt
  src/main/kotlin/org/openbase/planetsudo/view/util/JComboBoxExtensions.kt
Labels: bug, tested, code-approved

#37 Feature/4 agents should see some global states of the last seen adversary agent
  src/main/kotlin/org/openbase/planetsudo/game/GameSound.kt
  src/main/kotlin/org/openbase/planetsudo/game/strategy/AbstractStrategy.kt
  src/main/kotlin/org/openbase/planetsudo/game/strategy/DivineStrategy.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentMock.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/GlobalAgentInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/GlobalAgentProxy.kt
Labels: tested, code-approved
