Repository openbase/planetsudo.engine, pull requests merged in 2024-03, with the labels that each got.

#48 Fixed Tonic resource distribution on SimpleWorld.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/SimpleWorld.kt
Labels: tested, code-approved

#50 Fix #20 Clock displays wrong time
  src/main/kotlin/org/openbase/planetsudo/game/GameManager.kt
  src/main/kotlin/org/openbase/planetsudo/view/menu/LevelMenuPanel.kt
Labels: tested, code-approved

#53 Map editing
  src/main/kotlin/org/openbase/planetsudo/level/save/Arena.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Atomum.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/AtomumLight.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/BackToBack.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Broken.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/ChemStation.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/CircleOfLife.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/DasBoot.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Engpass.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Entropie.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/FrauenWG.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/HeliLandeplatz.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Hexagon.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/JD.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/LordHelmchen.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/LuckyLoop.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Maze.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Offensive.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/OffensiveBackdoor.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Pentagon.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/QuadratischPraktischBoese.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/QuadratischPraktischGut.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/Revolution.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/SimpleWorld.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/TwoKings.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/UTurn.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/UnbekannterWeg.kt
  src/main/kotlin/org/openbase/planetsudo/level/save/WakaWaka.kt
Labels: code-approved

#57 Fixed agents getting stuck over inaccessible resources
  src/main/kotlin/org/openbase/planetsudo/level/AbstractLevel.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Resource.kt
Labels: ready-to-review

#59 Implement GoToTeamAgent
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentBattleInterface.kt
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentMock.kt
Labels: feature, code-approved

#61 Fixed agents leaving map
  src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
Labels: ready-to-review
